### ISSUE TITLE
readthedocs run fails with "TypeError: connect() got an unexpected keyword argument 'priority'"

### ISSUE THREAD

**Issue by mithro** [SymbiFlow/python-symbiflow-v2x#43]
```
Running Sphinx v2.4.4
Docs dir is: /home/docs/checkouts/readthedocs.org/user_builds/python-symbiflow-v2x/checkouts/latest/docs
loading translations [en]... done

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/python-symbiflow-v2x/conda/latest/lib/python3.7/site-packages/sphinx/cmd/build.py", line 275, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/docs/checkouts/readthedocs.org/user_builds/python-symbiflow-v2x/conda/latest/lib/python3.7/site-packages/sphinx/application.py", line 241, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/python-symbiflow-v2x/conda/latest/lib/python3.7/site-packages/sphinx/application.py", line 397, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/python-symbiflow-v2x/conda/latest/lib/python3.7/site-packages/sphinx/registry.py", line 465, in load_extension
    metadata = setup(app)
  File "/home/docs/checkouts/readthedocs.org/user_builds/python-symbiflow-v2x/conda/latest/lib/python3.7/site-packages/sphinx/builders/dirhtml.py", line 58, in setup
    app.setup_extension('sphinx.builders.html')
  File "/home/docs/checkouts/readthedocs.org/user_builds/python-symbiflow-v2x/conda/latest/lib/python3.7/site-packages/sphinx/application.py", line 397, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/python-symbiflow-v2x/conda/latest/lib/python3.7/site-packages/sphinx/registry.py", line 465, in load_extension
    metadata = setup(app)
  File "/home/docs/checkouts/readthedocs.org/user_builds/python-symbiflow-v2x/conda/latest/lib/python3.7/site-packages/sphinx/builders/html/__init__.py", line 1234, in setup
    app.connect('config-inited', convert_html_css_files, priority=800)
TypeError: connect() got an unexpected keyword argument 'priority'

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/python-symbiflow-v2x/conda/latest/lib/python3.7/site-packages/sphinx/builders/html/__init__.py", line 1234, in setup
    app.connect('config-inited', convert_html_css_files, priority=800)
TypeError: connect() got an unexpected keyword argument 'priority'
The full traceback has been saved in /tmp/sphinx-err-dpsuq7ii.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

**Comment by mithro** [comment]
https://readthedocs.org/projects/python-symbiflow-v2x/builds/10838685/

**Comment by mithro** [comment]
Apparently the last success was;
```
Completed Feb. 10, 2020. 4:33 p.m.
Build took 258 seconds
View docs
View raw
Build #10413314
latest (4bc9809986693f9029e3871152d186849d7ca766)
Build completed
```

**Comment by mithro** [comment]
Issue seems to be https://github.com/readthedocs/readthedocs.org/issues/6870
